/**
 * {@link com.palyrobotics.frc2020.auto.AutoBase}'s placed in this package will automatically be
 * detected by {@link com.palyrobotics.frc2020.robot.AutoSelector}. This makes them visible for the
 * selector in Control Center, and also selectable via their name with
 * {@link com.palyrobotics.frc2020.robot.AutoSelector#setAuto(java.lang.String)}. Their name is
 * generated by default from the class name via
 * {@link com.palyrobotics.frc2020.auto.AutoBase#getName()}
 */
package com.palyrobotics.frc2020.auto;
